apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: surferseo-monitor
spec:
  selector:
    matchLabels:
      app: surferseo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: surferseo-alerts
spec:
  groups:
  - name: surferseo.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_request_duration_seconds_count{status_code=~"5.."}[5m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: "Error rate is above 5% for {{ $value }}% of requests"
    - alert: SlowResponses
      expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Slow response times
        description: "Average response time is {{ $value }}s"